// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package msg

/*
包名，通过protoc生成时go文件时
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 帐号登录
type U2S_Login struct {
	SdkAccount           string   `protobuf:"bytes,1,opt,name=SdkAccount,proto3" json:"SdkAccount,omitempty"`
	SdkClientID          string   `protobuf:"bytes,2,opt,name=SdkClientID,proto3" json:"SdkClientID,omitempty"`
	SdkAccessToken       string   `protobuf:"bytes,3,opt,name=SdkAccessToken,proto3" json:"SdkAccessToken,omitempty"`
	ChannelID            int32    `protobuf:"varint,4,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	GameVer              uint32   `protobuf:"varint,6,opt,name=GameVer,proto3" json:"GameVer,omitempty"`
	Extra                string   `protobuf:"bytes,7,opt,name=Extra,proto3" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *U2S_Login) Reset()         { *m = U2S_Login{} }
func (m *U2S_Login) String() string { return proto.CompactTextString(m) }
func (*U2S_Login) ProtoMessage()    {}
func (*U2S_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{0}
}
func (m *U2S_Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_U2S_Login.Unmarshal(m, b)
}
func (m *U2S_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_U2S_Login.Marshal(b, m, deterministic)
}
func (dst *U2S_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_U2S_Login.Merge(dst, src)
}
func (m *U2S_Login) XXX_Size() int {
	return xxx_messageInfo_U2S_Login.Size(m)
}
func (m *U2S_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_U2S_Login.DiscardUnknown(m)
}

var xxx_messageInfo_U2S_Login proto.InternalMessageInfo

func (m *U2S_Login) GetSdkAccount() string {
	if m != nil {
		return m.SdkAccount
	}
	return ""
}

func (m *U2S_Login) GetSdkClientID() string {
	if m != nil {
		return m.SdkClientID
	}
	return ""
}

func (m *U2S_Login) GetSdkAccessToken() string {
	if m != nil {
		return m.SdkAccessToken
	}
	return ""
}

func (m *U2S_Login) GetChannelID() int32 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *U2S_Login) GetGameVer() uint32 {
	if m != nil {
		return m.GameVer
	}
	return 0
}

func (m *U2S_Login) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

// 帐号登录反馈
type S2U_LoginResult struct {
	Result               uint32   `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
	Gametoken            int64    `protobuf:"varint,3,opt,name=Gametoken,proto3" json:"Gametoken,omitempty"`
	Msg                  string   `protobuf:"bytes,4,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2U_LoginResult) Reset()         { *m = S2U_LoginResult{} }
func (m *S2U_LoginResult) String() string { return proto.CompactTextString(m) }
func (*S2U_LoginResult) ProtoMessage()    {}
func (*S2U_LoginResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{1}
}
func (m *S2U_LoginResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2U_LoginResult.Unmarshal(m, b)
}
func (m *S2U_LoginResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2U_LoginResult.Marshal(b, m, deterministic)
}
func (dst *S2U_LoginResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2U_LoginResult.Merge(dst, src)
}
func (m *S2U_LoginResult) XXX_Size() int {
	return xxx_messageInfo_S2U_LoginResult.Size(m)
}
func (m *S2U_LoginResult) XXX_DiscardUnknown() {
	xxx_messageInfo_S2U_LoginResult.DiscardUnknown(m)
}

var xxx_messageInfo_S2U_LoginResult proto.InternalMessageInfo

func (m *S2U_LoginResult) GetResult() uint32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *S2U_LoginResult) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *S2U_LoginResult) GetGametoken() int64 {
	if m != nil {
		return m.Gametoken
	}
	return 0
}

func (m *S2U_LoginResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// 帐号注册
type U2S_RegistAccount struct {
	SdkAccount           string   `protobuf:"bytes,1,opt,name=SdkAccount,proto3" json:"SdkAccount,omitempty"`
	SdkClientID          string   `protobuf:"bytes,2,opt,name=SdkClientID,proto3" json:"SdkClientID,omitempty"`
	SdkAccessToken       string   `protobuf:"bytes,3,opt,name=SdkAccessToken,proto3" json:"SdkAccessToken,omitempty"`
	ChannelID            int32    `protobuf:"varint,4,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	Imei                 string   `protobuf:"bytes,5,opt,name=Imei,proto3" json:"Imei,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=Name,proto3" json:"Name,omitempty"`
	Style                uint32   `protobuf:"varint,8,opt,name=Style,proto3" json:"Style,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *U2S_RegistAccount) Reset()         { *m = U2S_RegistAccount{} }
func (m *U2S_RegistAccount) String() string { return proto.CompactTextString(m) }
func (*U2S_RegistAccount) ProtoMessage()    {}
func (*U2S_RegistAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{2}
}
func (m *U2S_RegistAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_U2S_RegistAccount.Unmarshal(m, b)
}
func (m *U2S_RegistAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_U2S_RegistAccount.Marshal(b, m, deterministic)
}
func (dst *U2S_RegistAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_U2S_RegistAccount.Merge(dst, src)
}
func (m *U2S_RegistAccount) XXX_Size() int {
	return xxx_messageInfo_U2S_RegistAccount.Size(m)
}
func (m *U2S_RegistAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_U2S_RegistAccount.DiscardUnknown(m)
}

var xxx_messageInfo_U2S_RegistAccount proto.InternalMessageInfo

func (m *U2S_RegistAccount) GetSdkAccount() string {
	if m != nil {
		return m.SdkAccount
	}
	return ""
}

func (m *U2S_RegistAccount) GetSdkClientID() string {
	if m != nil {
		return m.SdkClientID
	}
	return ""
}

func (m *U2S_RegistAccount) GetSdkAccessToken() string {
	if m != nil {
		return m.SdkAccessToken
	}
	return ""
}

func (m *U2S_RegistAccount) GetChannelID() int32 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *U2S_RegistAccount) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *U2S_RegistAccount) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *U2S_RegistAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *U2S_RegistAccount) GetStyle() uint32 {
	if m != nil {
		return m.Style
	}
	return 0
}

// 帐号注册反馈
type G2U_RegistAccountResult struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *G2U_RegistAccountResult) Reset()         { *m = G2U_RegistAccountResult{} }
func (m *G2U_RegistAccountResult) String() string { return proto.CompactTextString(m) }
func (*G2U_RegistAccountResult) ProtoMessage()    {}
func (*G2U_RegistAccountResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{3}
}
func (m *G2U_RegistAccountResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_G2U_RegistAccountResult.Unmarshal(m, b)
}
func (m *G2U_RegistAccountResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_G2U_RegistAccountResult.Marshal(b, m, deterministic)
}
func (dst *G2U_RegistAccountResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_G2U_RegistAccountResult.Merge(dst, src)
}
func (m *G2U_RegistAccountResult) XXX_Size() int {
	return xxx_messageInfo_G2U_RegistAccountResult.Size(m)
}
func (m *G2U_RegistAccountResult) XXX_DiscardUnknown() {
	xxx_messageInfo_G2U_RegistAccountResult.DiscardUnknown(m)
}

var xxx_messageInfo_G2U_RegistAccountResult proto.InternalMessageInfo

func (m *G2U_RegistAccountResult) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 帐号信息
type S2U_PlayerBase struct {
	PlayerID             uint32   `protobuf:"varint,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Style                uint32   `protobuf:"varint,4,opt,name=Style,proto3" json:"Style,omitempty"`
	AppCoins             float32  `protobuf:"fixed32,5,opt,name=AppCoins,proto3" json:"AppCoins,omitempty"`
	ComputePower         float32  `protobuf:"fixed32,6,opt,name=ComputePower,proto3" json:"ComputePower,omitempty"`
	Btc                  float32  `protobuf:"fixed32,7,opt,name=Btc,proto3" json:"Btc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2U_PlayerBase) Reset()         { *m = S2U_PlayerBase{} }
func (m *S2U_PlayerBase) String() string { return proto.CompactTextString(m) }
func (*S2U_PlayerBase) ProtoMessage()    {}
func (*S2U_PlayerBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{4}
}
func (m *S2U_PlayerBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2U_PlayerBase.Unmarshal(m, b)
}
func (m *S2U_PlayerBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2U_PlayerBase.Marshal(b, m, deterministic)
}
func (dst *S2U_PlayerBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2U_PlayerBase.Merge(dst, src)
}
func (m *S2U_PlayerBase) XXX_Size() int {
	return xxx_messageInfo_S2U_PlayerBase.Size(m)
}
func (m *S2U_PlayerBase) XXX_DiscardUnknown() {
	xxx_messageInfo_S2U_PlayerBase.DiscardUnknown(m)
}

var xxx_messageInfo_S2U_PlayerBase proto.InternalMessageInfo

func (m *S2U_PlayerBase) GetPlayerID() uint32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *S2U_PlayerBase) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *S2U_PlayerBase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *S2U_PlayerBase) GetStyle() uint32 {
	if m != nil {
		return m.Style
	}
	return 0
}

func (m *S2U_PlayerBase) GetAppCoins() float32 {
	if m != nil {
		return m.AppCoins
	}
	return 0
}

func (m *S2U_PlayerBase) GetComputePower() float32 {
	if m != nil {
		return m.ComputePower
	}
	return 0
}

func (m *S2U_PlayerBase) GetBtc() float32 {
	if m != nil {
		return m.Btc
	}
	return 0
}

// 公告
type S2U_Notice struct {
	Type                 int32    `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Msg                  []byte   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2U_Notice) Reset()         { *m = S2U_Notice{} }
func (m *S2U_Notice) String() string { return proto.CompactTextString(m) }
func (*S2U_Notice) ProtoMessage()    {}
func (*S2U_Notice) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{5}
}
func (m *S2U_Notice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2U_Notice.Unmarshal(m, b)
}
func (m *S2U_Notice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2U_Notice.Marshal(b, m, deterministic)
}
func (dst *S2U_Notice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2U_Notice.Merge(dst, src)
}
func (m *S2U_Notice) XXX_Size() int {
	return xxx_messageInfo_S2U_Notice.Size(m)
}
func (m *S2U_Notice) XXX_DiscardUnknown() {
	xxx_messageInfo_S2U_Notice.DiscardUnknown(m)
}

var xxx_messageInfo_S2U_Notice proto.InternalMessageInfo

func (m *S2U_Notice) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *S2U_Notice) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

// 聊天上行
type U2S_Chat struct {
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *U2S_Chat) Reset()         { *m = U2S_Chat{} }
func (m *U2S_Chat) String() string { return proto.CompactTextString(m) }
func (*U2S_Chat) ProtoMessage()    {}
func (*U2S_Chat) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{6}
}
func (m *U2S_Chat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_U2S_Chat.Unmarshal(m, b)
}
func (m *U2S_Chat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_U2S_Chat.Marshal(b, m, deterministic)
}
func (dst *U2S_Chat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_U2S_Chat.Merge(dst, src)
}
func (m *U2S_Chat) XXX_Size() int {
	return xxx_messageInfo_U2S_Chat.Size(m)
}
func (m *U2S_Chat) XXX_DiscardUnknown() {
	xxx_messageInfo_U2S_Chat.DiscardUnknown(m)
}

var xxx_messageInfo_U2S_Chat proto.InternalMessageInfo

func (m *U2S_Chat) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// 聊天下发
type S2U_Chat struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Style                uint32   `protobuf:"varint,2,opt,name=Style,proto3" json:"Style,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2U_Chat) Reset()         { *m = S2U_Chat{} }
func (m *S2U_Chat) String() string { return proto.CompactTextString(m) }
func (*S2U_Chat) ProtoMessage()    {}
func (*S2U_Chat) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{7}
}
func (m *S2U_Chat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2U_Chat.Unmarshal(m, b)
}
func (m *S2U_Chat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2U_Chat.Marshal(b, m, deterministic)
}
func (dst *S2U_Chat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2U_Chat.Merge(dst, src)
}
func (m *S2U_Chat) XXX_Size() int {
	return xxx_messageInfo_S2U_Chat.Size(m)
}
func (m *S2U_Chat) XXX_DiscardUnknown() {
	xxx_messageInfo_S2U_Chat.DiscardUnknown(m)
}

var xxx_messageInfo_S2U_Chat proto.InternalMessageInfo

func (m *S2U_Chat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *S2U_Chat) GetStyle() uint32 {
	if m != nil {
		return m.Style
	}
	return 0
}

func (m *S2U_Chat) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// 打开商城
type U2S_ShopList struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *U2S_ShopList) Reset()         { *m = U2S_ShopList{} }
func (m *U2S_ShopList) String() string { return proto.CompactTextString(m) }
func (*U2S_ShopList) ProtoMessage()    {}
func (*U2S_ShopList) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{8}
}
func (m *U2S_ShopList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_U2S_ShopList.Unmarshal(m, b)
}
func (m *U2S_ShopList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_U2S_ShopList.Marshal(b, m, deterministic)
}
func (dst *U2S_ShopList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_U2S_ShopList.Merge(dst, src)
}
func (m *U2S_ShopList) XXX_Size() int {
	return xxx_messageInfo_U2S_ShopList.Size(m)
}
func (m *U2S_ShopList) XXX_DiscardUnknown() {
	xxx_messageInfo_U2S_ShopList.DiscardUnknown(m)
}

var xxx_messageInfo_U2S_ShopList proto.InternalMessageInfo

// 商品名明细	价格，库存，电费，管理费，产出币
type ShopInfo struct {
	ProductID            int32    `protobuf:"varint,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Repertory            int32    `protobuf:"varint,2,opt,name=repertory,proto3" json:"repertory,omitempty"`
	Electric             float32  `protobuf:"fixed32,3,opt,name=electric,proto3" json:"electric,omitempty"`
	ManageCost           float32  `protobuf:"fixed32,4,opt,name=manageCost,proto3" json:"manageCost,omitempty"`
	Output               float32  `protobuf:"fixed32,5,opt,name=output,proto3" json:"output,omitempty"`
	Price                float32  `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopInfo) Reset()         { *m = ShopInfo{} }
func (m *ShopInfo) String() string { return proto.CompactTextString(m) }
func (*ShopInfo) ProtoMessage()    {}
func (*ShopInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{9}
}
func (m *ShopInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopInfo.Unmarshal(m, b)
}
func (m *ShopInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopInfo.Marshal(b, m, deterministic)
}
func (dst *ShopInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopInfo.Merge(dst, src)
}
func (m *ShopInfo) XXX_Size() int {
	return xxx_messageInfo_ShopInfo.Size(m)
}
func (m *ShopInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ShopInfo proto.InternalMessageInfo

func (m *ShopInfo) GetProductID() int32 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

func (m *ShopInfo) GetRepertory() int32 {
	if m != nil {
		return m.Repertory
	}
	return 0
}

func (m *ShopInfo) GetElectric() float32 {
	if m != nil {
		return m.Electric
	}
	return 0
}

func (m *ShopInfo) GetManageCost() float32 {
	if m != nil {
		return m.ManageCost
	}
	return 0
}

func (m *ShopInfo) GetOutput() float32 {
	if m != nil {
		return m.Output
	}
	return 0
}

func (m *ShopInfo) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

// 商城信息
type S2U_ShopList struct {
	List                 []*ShopInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *S2U_ShopList) Reset()         { *m = S2U_ShopList{} }
func (m *S2U_ShopList) String() string { return proto.CompactTextString(m) }
func (*S2U_ShopList) ProtoMessage()    {}
func (*S2U_ShopList) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{10}
}
func (m *S2U_ShopList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2U_ShopList.Unmarshal(m, b)
}
func (m *S2U_ShopList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2U_ShopList.Marshal(b, m, deterministic)
}
func (dst *S2U_ShopList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2U_ShopList.Merge(dst, src)
}
func (m *S2U_ShopList) XXX_Size() int {
	return xxx_messageInfo_S2U_ShopList.Size(m)
}
func (m *S2U_ShopList) XXX_DiscardUnknown() {
	xxx_messageInfo_S2U_ShopList.DiscardUnknown(m)
}

var xxx_messageInfo_S2U_ShopList proto.InternalMessageInfo

func (m *S2U_ShopList) GetList() []*ShopInfo {
	if m != nil {
		return m.List
	}
	return nil
}

// 购买矿机
type U2S_Buy struct {
	ProductID            int32    `protobuf:"varint,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *U2S_Buy) Reset()         { *m = U2S_Buy{} }
func (m *U2S_Buy) String() string { return proto.CompactTextString(m) }
func (*U2S_Buy) ProtoMessage()    {}
func (*U2S_Buy) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{11}
}
func (m *U2S_Buy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_U2S_Buy.Unmarshal(m, b)
}
func (m *U2S_Buy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_U2S_Buy.Marshal(b, m, deterministic)
}
func (dst *U2S_Buy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_U2S_Buy.Merge(dst, src)
}
func (m *U2S_Buy) XXX_Size() int {
	return xxx_messageInfo_U2S_Buy.Size(m)
}
func (m *U2S_Buy) XXX_DiscardUnknown() {
	xxx_messageInfo_U2S_Buy.DiscardUnknown(m)
}

var xxx_messageInfo_U2S_Buy proto.InternalMessageInfo

func (m *U2S_Buy) GetProductID() int32 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

func (m *U2S_Buy) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 购买矿机反馈
type S2U_BuyResult struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2U_BuyResult) Reset()         { *m = S2U_BuyResult{} }
func (m *S2U_BuyResult) String() string { return proto.CompactTextString(m) }
func (*S2U_BuyResult) ProtoMessage()    {}
func (*S2U_BuyResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{12}
}
func (m *S2U_BuyResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2U_BuyResult.Unmarshal(m, b)
}
func (m *S2U_BuyResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2U_BuyResult.Marshal(b, m, deterministic)
}
func (dst *S2U_BuyResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2U_BuyResult.Merge(dst, src)
}
func (m *S2U_BuyResult) XXX_Size() int {
	return xxx_messageInfo_S2U_BuyResult.Size(m)
}
func (m *S2U_BuyResult) XXX_DiscardUnknown() {
	xxx_messageInfo_S2U_BuyResult.DiscardUnknown(m)
}

var xxx_messageInfo_S2U_BuyResult proto.InternalMessageInfo

func (m *S2U_BuyResult) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 请求矿机信息
type U2S_MineMachineList struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *U2S_MineMachineList) Reset()         { *m = U2S_MineMachineList{} }
func (m *U2S_MineMachineList) String() string { return proto.CompactTextString(m) }
func (*U2S_MineMachineList) ProtoMessage()    {}
func (*U2S_MineMachineList) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{13}
}
func (m *U2S_MineMachineList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_U2S_MineMachineList.Unmarshal(m, b)
}
func (m *U2S_MineMachineList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_U2S_MineMachineList.Marshal(b, m, deterministic)
}
func (dst *U2S_MineMachineList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_U2S_MineMachineList.Merge(dst, src)
}
func (m *U2S_MineMachineList) XXX_Size() int {
	return xxx_messageInfo_U2S_MineMachineList.Size(m)
}
func (m *U2S_MineMachineList) XXX_DiscardUnknown() {
	xxx_messageInfo_U2S_MineMachineList.DiscardUnknown(m)
}

var xxx_messageInfo_U2S_MineMachineList proto.InternalMessageInfo

// 矿机信息
type MineMachine struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ProductID            int32    `protobuf:"varint,2,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Location             int32    `protobuf:"varint,3,opt,name=Location,proto3" json:"Location,omitempty"`
	RunTime              int64    `protobuf:"varint,4,opt,name=RunTime,proto3" json:"RunTime,omitempty"`
	EndTime              int64    `protobuf:"varint,5,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	OutputCoin           float32  `protobuf:"fixed32,6,opt,name=OutputCoin,proto3" json:"OutputCoin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MineMachine) Reset()         { *m = MineMachine{} }
func (m *MineMachine) String() string { return proto.CompactTextString(m) }
func (*MineMachine) ProtoMessage()    {}
func (*MineMachine) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{14}
}
func (m *MineMachine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MineMachine.Unmarshal(m, b)
}
func (m *MineMachine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MineMachine.Marshal(b, m, deterministic)
}
func (dst *MineMachine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MineMachine.Merge(dst, src)
}
func (m *MineMachine) XXX_Size() int {
	return xxx_messageInfo_MineMachine.Size(m)
}
func (m *MineMachine) XXX_DiscardUnknown() {
	xxx_messageInfo_MineMachine.DiscardUnknown(m)
}

var xxx_messageInfo_MineMachine proto.InternalMessageInfo

func (m *MineMachine) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MineMachine) GetProductID() int32 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

func (m *MineMachine) GetLocation() int32 {
	if m != nil {
		return m.Location
	}
	return 0
}

func (m *MineMachine) GetRunTime() int64 {
	if m != nil {
		return m.RunTime
	}
	return 0
}

func (m *MineMachine) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *MineMachine) GetOutputCoin() float32 {
	if m != nil {
		return m.OutputCoin
	}
	return 0
}

// 玩家所属矿机列表
type S2U_MineMachineList struct {
	List                 []*MineMachine `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2U_MineMachineList) Reset()         { *m = S2U_MineMachineList{} }
func (m *S2U_MineMachineList) String() string { return proto.CompactTextString(m) }
func (*S2U_MineMachineList) ProtoMessage()    {}
func (*S2U_MineMachineList) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{15}
}
func (m *S2U_MineMachineList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2U_MineMachineList.Unmarshal(m, b)
}
func (m *S2U_MineMachineList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2U_MineMachineList.Marshal(b, m, deterministic)
}
func (dst *S2U_MineMachineList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2U_MineMachineList.Merge(dst, src)
}
func (m *S2U_MineMachineList) XXX_Size() int {
	return xxx_messageInfo_S2U_MineMachineList.Size(m)
}
func (m *S2U_MineMachineList) XXX_DiscardUnknown() {
	xxx_messageInfo_S2U_MineMachineList.DiscardUnknown(m)
}

var xxx_messageInfo_S2U_MineMachineList proto.InternalMessageInfo

func (m *S2U_MineMachineList) GetList() []*MineMachine {
	if m != nil {
		return m.List
	}
	return nil
}

// 请求矿点列表
type U2S_MineList struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *U2S_MineList) Reset()         { *m = U2S_MineList{} }
func (m *U2S_MineList) String() string { return proto.CompactTextString(m) }
func (*U2S_MineList) ProtoMessage()    {}
func (*U2S_MineList) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{16}
}
func (m *U2S_MineList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_U2S_MineList.Unmarshal(m, b)
}
func (m *U2S_MineList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_U2S_MineList.Marshal(b, m, deterministic)
}
func (dst *U2S_MineList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_U2S_MineList.Merge(dst, src)
}
func (m *U2S_MineList) XXX_Size() int {
	return xxx_messageInfo_U2S_MineList.Size(m)
}
func (m *U2S_MineList) XXX_DiscardUnknown() {
	xxx_messageInfo_U2S_MineList.DiscardUnknown(m)
}

var xxx_messageInfo_U2S_MineList proto.InternalMessageInfo

// 矿点名明细	序号，电费，管理费，效率，剩余机位
type MineInfo struct {
	Location             int32    `protobuf:"varint,1,opt,name=Location,proto3" json:"Location,omitempty"`
	Electric             float32  `protobuf:"fixed32,2,opt,name=Electric,proto3" json:"Electric,omitempty"`
	Tip                  float32  `protobuf:"fixed32,3,opt,name=Tip,proto3" json:"Tip,omitempty"`
	Ratio                float32  `protobuf:"fixed32,4,opt,name=Ratio,proto3" json:"Ratio,omitempty"`
	Num                  int32    `protobuf:"varint,5,opt,name=Num,proto3" json:"Num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MineInfo) Reset()         { *m = MineInfo{} }
func (m *MineInfo) String() string { return proto.CompactTextString(m) }
func (*MineInfo) ProtoMessage()    {}
func (*MineInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{17}
}
func (m *MineInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MineInfo.Unmarshal(m, b)
}
func (m *MineInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MineInfo.Marshal(b, m, deterministic)
}
func (dst *MineInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MineInfo.Merge(dst, src)
}
func (m *MineInfo) XXX_Size() int {
	return xxx_messageInfo_MineInfo.Size(m)
}
func (m *MineInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MineInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MineInfo proto.InternalMessageInfo

func (m *MineInfo) GetLocation() int32 {
	if m != nil {
		return m.Location
	}
	return 0
}

func (m *MineInfo) GetElectric() float32 {
	if m != nil {
		return m.Electric
	}
	return 0
}

func (m *MineInfo) GetTip() float32 {
	if m != nil {
		return m.Tip
	}
	return 0
}

func (m *MineInfo) GetRatio() float32 {
	if m != nil {
		return m.Ratio
	}
	return 0
}

func (m *MineInfo) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

// 矿点信息
type S2U_MineList struct {
	List                 []*MineInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *S2U_MineList) Reset()         { *m = S2U_MineList{} }
func (m *S2U_MineList) String() string { return proto.CompactTextString(m) }
func (*S2U_MineList) ProtoMessage()    {}
func (*S2U_MineList) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{18}
}
func (m *S2U_MineList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2U_MineList.Unmarshal(m, b)
}
func (m *S2U_MineList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2U_MineList.Marshal(b, m, deterministic)
}
func (dst *S2U_MineList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2U_MineList.Merge(dst, src)
}
func (m *S2U_MineList) XXX_Size() int {
	return xxx_messageInfo_S2U_MineList.Size(m)
}
func (m *S2U_MineList) XXX_DiscardUnknown() {
	xxx_messageInfo_S2U_MineList.DiscardUnknown(m)
}

var xxx_messageInfo_S2U_MineList proto.InternalMessageInfo

func (m *S2U_MineList) GetList() []*MineInfo {
	if m != nil {
		return m.List
	}
	return nil
}

// 开始挖矿
type U2S_Mining struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Location             int32    `protobuf:"varint,2,opt,name=Location,proto3" json:"Location,omitempty"`
	WillDay              int32    `protobuf:"varint,3,opt,name=WillDay,proto3" json:"WillDay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *U2S_Mining) Reset()         { *m = U2S_Mining{} }
func (m *U2S_Mining) String() string { return proto.CompactTextString(m) }
func (*U2S_Mining) ProtoMessage()    {}
func (*U2S_Mining) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{19}
}
func (m *U2S_Mining) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_U2S_Mining.Unmarshal(m, b)
}
func (m *U2S_Mining) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_U2S_Mining.Marshal(b, m, deterministic)
}
func (dst *U2S_Mining) XXX_Merge(src proto.Message) {
	xxx_messageInfo_U2S_Mining.Merge(dst, src)
}
func (m *U2S_Mining) XXX_Size() int {
	return xxx_messageInfo_U2S_Mining.Size(m)
}
func (m *U2S_Mining) XXX_DiscardUnknown() {
	xxx_messageInfo_U2S_Mining.DiscardUnknown(m)
}

var xxx_messageInfo_U2S_Mining proto.InternalMessageInfo

func (m *U2S_Mining) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *U2S_Mining) GetLocation() int32 {
	if m != nil {
		return m.Location
	}
	return 0
}

func (m *U2S_Mining) GetWillDay() int32 {
	if m != nil {
		return m.WillDay
	}
	return 0
}

// 挖矿操作反馈
type S2U_MiningResult struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2U_MiningResult) Reset()         { *m = S2U_MiningResult{} }
func (m *S2U_MiningResult) String() string { return proto.CompactTextString(m) }
func (*S2U_MiningResult) ProtoMessage()    {}
func (*S2U_MiningResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{20}
}
func (m *S2U_MiningResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2U_MiningResult.Unmarshal(m, b)
}
func (m *S2U_MiningResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2U_MiningResult.Marshal(b, m, deterministic)
}
func (dst *S2U_MiningResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2U_MiningResult.Merge(dst, src)
}
func (m *S2U_MiningResult) XXX_Size() int {
	return xxx_messageInfo_S2U_MiningResult.Size(m)
}
func (m *S2U_MiningResult) XXX_DiscardUnknown() {
	xxx_messageInfo_S2U_MiningResult.DiscardUnknown(m)
}

var xxx_messageInfo_S2U_MiningResult proto.InternalMessageInfo

func (m *S2U_MiningResult) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *S2U_MiningResult) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 收集矿
type U2S_GatherMine struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Location             int32    `protobuf:"varint,2,opt,name=Location,proto3" json:"Location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *U2S_GatherMine) Reset()         { *m = U2S_GatherMine{} }
func (m *U2S_GatherMine) String() string { return proto.CompactTextString(m) }
func (*U2S_GatherMine) ProtoMessage()    {}
func (*U2S_GatherMine) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{21}
}
func (m *U2S_GatherMine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_U2S_GatherMine.Unmarshal(m, b)
}
func (m *U2S_GatherMine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_U2S_GatherMine.Marshal(b, m, deterministic)
}
func (dst *U2S_GatherMine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_U2S_GatherMine.Merge(dst, src)
}
func (m *U2S_GatherMine) XXX_Size() int {
	return xxx_messageInfo_U2S_GatherMine.Size(m)
}
func (m *U2S_GatherMine) XXX_DiscardUnknown() {
	xxx_messageInfo_U2S_GatherMine.DiscardUnknown(m)
}

var xxx_messageInfo_U2S_GatherMine proto.InternalMessageInfo

func (m *U2S_GatherMine) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *U2S_GatherMine) GetLocation() int32 {
	if m != nil {
		return m.Location
	}
	return 0
}

// 收集矿反馈
type S2U_GatherMine struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Btc                  float32  `protobuf:"fixed32,2,opt,name=Btc,proto3" json:"Btc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2U_GatherMine) Reset()         { *m = S2U_GatherMine{} }
func (m *S2U_GatherMine) String() string { return proto.CompactTextString(m) }
func (*S2U_GatherMine) ProtoMessage()    {}
func (*S2U_GatherMine) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{22}
}
func (m *S2U_GatherMine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2U_GatherMine.Unmarshal(m, b)
}
func (m *S2U_GatherMine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2U_GatherMine.Marshal(b, m, deterministic)
}
func (dst *S2U_GatherMine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2U_GatherMine.Merge(dst, src)
}
func (m *S2U_GatherMine) XXX_Size() int {
	return xxx_messageInfo_S2U_GatherMine.Size(m)
}
func (m *S2U_GatherMine) XXX_DiscardUnknown() {
	xxx_messageInfo_S2U_GatherMine.DiscardUnknown(m)
}

var xxx_messageInfo_S2U_GatherMine proto.InternalMessageInfo

func (m *S2U_GatherMine) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *S2U_GatherMine) GetBtc() float32 {
	if m != nil {
		return m.Btc
	}
	return 0
}

// 停止挖矿
type U2S_StopMining struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *U2S_StopMining) Reset()         { *m = U2S_StopMining{} }
func (m *U2S_StopMining) String() string { return proto.CompactTextString(m) }
func (*U2S_StopMining) ProtoMessage()    {}
func (*U2S_StopMining) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{23}
}
func (m *U2S_StopMining) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_U2S_StopMining.Unmarshal(m, b)
}
func (m *U2S_StopMining) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_U2S_StopMining.Marshal(b, m, deterministic)
}
func (dst *U2S_StopMining) XXX_Merge(src proto.Message) {
	xxx_messageInfo_U2S_StopMining.Merge(dst, src)
}
func (m *U2S_StopMining) XXX_Size() int {
	return xxx_messageInfo_U2S_StopMining.Size(m)
}
func (m *U2S_StopMining) XXX_DiscardUnknown() {
	xxx_messageInfo_U2S_StopMining.DiscardUnknown(m)
}

var xxx_messageInfo_U2S_StopMining proto.InternalMessageInfo

func (m *U2S_StopMining) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

// 停止挖矿
type S2U_StopMiningResult struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2U_StopMiningResult) Reset()         { *m = S2U_StopMiningResult{} }
func (m *S2U_StopMiningResult) String() string { return proto.CompactTextString(m) }
func (*S2U_StopMiningResult) ProtoMessage()    {}
func (*S2U_StopMiningResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{24}
}
func (m *S2U_StopMiningResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2U_StopMiningResult.Unmarshal(m, b)
}
func (m *S2U_StopMiningResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2U_StopMiningResult.Marshal(b, m, deterministic)
}
func (dst *S2U_StopMiningResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2U_StopMiningResult.Merge(dst, src)
}
func (m *S2U_StopMiningResult) XXX_Size() int {
	return xxx_messageInfo_S2U_StopMiningResult.Size(m)
}
func (m *S2U_StopMiningResult) XXX_DiscardUnknown() {
	xxx_messageInfo_S2U_StopMiningResult.DiscardUnknown(m)
}

var xxx_messageInfo_S2U_StopMiningResult proto.InternalMessageInfo

func (m *S2U_StopMiningResult) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *S2U_StopMiningResult) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 更新玩家信息
type U2S_ModifyPlayer struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Style                uint32   `protobuf:"varint,2,opt,name=Style,proto3" json:"Style,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *U2S_ModifyPlayer) Reset()         { *m = U2S_ModifyPlayer{} }
func (m *U2S_ModifyPlayer) String() string { return proto.CompactTextString(m) }
func (*U2S_ModifyPlayer) ProtoMessage()    {}
func (*U2S_ModifyPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{25}
}
func (m *U2S_ModifyPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_U2S_ModifyPlayer.Unmarshal(m, b)
}
func (m *U2S_ModifyPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_U2S_ModifyPlayer.Marshal(b, m, deterministic)
}
func (dst *U2S_ModifyPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_U2S_ModifyPlayer.Merge(dst, src)
}
func (m *U2S_ModifyPlayer) XXX_Size() int {
	return xxx_messageInfo_U2S_ModifyPlayer.Size(m)
}
func (m *U2S_ModifyPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_U2S_ModifyPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_U2S_ModifyPlayer proto.InternalMessageInfo

func (m *U2S_ModifyPlayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *U2S_ModifyPlayer) GetStyle() uint32 {
	if m != nil {
		return m.Style
	}
	return 0
}

// 更新玩家信息
type S2U_ModifyPlayer struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2U_ModifyPlayer) Reset()         { *m = S2U_ModifyPlayer{} }
func (m *S2U_ModifyPlayer) String() string { return proto.CompactTextString(m) }
func (*S2U_ModifyPlayer) ProtoMessage()    {}
func (*S2U_ModifyPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{26}
}
func (m *S2U_ModifyPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2U_ModifyPlayer.Unmarshal(m, b)
}
func (m *S2U_ModifyPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2U_ModifyPlayer.Marshal(b, m, deterministic)
}
func (dst *S2U_ModifyPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2U_ModifyPlayer.Merge(dst, src)
}
func (m *S2U_ModifyPlayer) XXX_Size() int {
	return xxx_messageInfo_S2U_ModifyPlayer.Size(m)
}
func (m *S2U_ModifyPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_S2U_ModifyPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_S2U_ModifyPlayer proto.InternalMessageInfo

func (m *S2U_ModifyPlayer) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 请求排行榜
type U2S_Rank struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *U2S_Rank) Reset()         { *m = U2S_Rank{} }
func (m *U2S_Rank) String() string { return proto.CompactTextString(m) }
func (*U2S_Rank) ProtoMessage()    {}
func (*U2S_Rank) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{27}
}
func (m *U2S_Rank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_U2S_Rank.Unmarshal(m, b)
}
func (m *U2S_Rank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_U2S_Rank.Marshal(b, m, deterministic)
}
func (dst *U2S_Rank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_U2S_Rank.Merge(dst, src)
}
func (m *U2S_Rank) XXX_Size() int {
	return xxx_messageInfo_U2S_Rank.Size(m)
}
func (m *U2S_Rank) XXX_DiscardUnknown() {
	xxx_messageInfo_U2S_Rank.DiscardUnknown(m)
}

var xxx_messageInfo_U2S_Rank proto.InternalMessageInfo

// 排行榜单行数据
type RankInfo struct {
	NoID                 uint32   `protobuf:"varint,1,opt,name=NoID,proto3" json:"NoID,omitempty"`
	PlayerID             uint32   `protobuf:"varint,2,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Style                uint32   `protobuf:"varint,4,opt,name=Style,proto3" json:"Style,omitempty"`
	Value                float32  `protobuf:"fixed32,5,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RankInfo) Reset()         { *m = RankInfo{} }
func (m *RankInfo) String() string { return proto.CompactTextString(m) }
func (*RankInfo) ProtoMessage()    {}
func (*RankInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{28}
}
func (m *RankInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankInfo.Unmarshal(m, b)
}
func (m *RankInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankInfo.Marshal(b, m, deterministic)
}
func (dst *RankInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankInfo.Merge(dst, src)
}
func (m *RankInfo) XXX_Size() int {
	return xxx_messageInfo_RankInfo.Size(m)
}
func (m *RankInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RankInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RankInfo proto.InternalMessageInfo

func (m *RankInfo) GetNoID() uint32 {
	if m != nil {
		return m.NoID
	}
	return 0
}

func (m *RankInfo) GetPlayerID() uint32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *RankInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RankInfo) GetStyle() uint32 {
	if m != nil {
		return m.Style
	}
	return 0
}

func (m *RankInfo) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

// 游戏币排行榜
type S2U_AppCoinRank struct {
	List                 []*RankInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *S2U_AppCoinRank) Reset()         { *m = S2U_AppCoinRank{} }
func (m *S2U_AppCoinRank) String() string { return proto.CompactTextString(m) }
func (*S2U_AppCoinRank) ProtoMessage()    {}
func (*S2U_AppCoinRank) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{29}
}
func (m *S2U_AppCoinRank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2U_AppCoinRank.Unmarshal(m, b)
}
func (m *S2U_AppCoinRank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2U_AppCoinRank.Marshal(b, m, deterministic)
}
func (dst *S2U_AppCoinRank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2U_AppCoinRank.Merge(dst, src)
}
func (m *S2U_AppCoinRank) XXX_Size() int {
	return xxx_messageInfo_S2U_AppCoinRank.Size(m)
}
func (m *S2U_AppCoinRank) XXX_DiscardUnknown() {
	xxx_messageInfo_S2U_AppCoinRank.DiscardUnknown(m)
}

var xxx_messageInfo_S2U_AppCoinRank proto.InternalMessageInfo

func (m *S2U_AppCoinRank) GetList() []*RankInfo {
	if m != nil {
		return m.List
	}
	return nil
}

// 今日产出（比特币）排行榜
type S2U_BtcRank struct {
	List                 []*RankInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *S2U_BtcRank) Reset()         { *m = S2U_BtcRank{} }
func (m *S2U_BtcRank) String() string { return proto.CompactTextString(m) }
func (*S2U_BtcRank) ProtoMessage()    {}
func (*S2U_BtcRank) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0cde66bc4e56949c, []int{30}
}
func (m *S2U_BtcRank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2U_BtcRank.Unmarshal(m, b)
}
func (m *S2U_BtcRank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2U_BtcRank.Marshal(b, m, deterministic)
}
func (dst *S2U_BtcRank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2U_BtcRank.Merge(dst, src)
}
func (m *S2U_BtcRank) XXX_Size() int {
	return xxx_messageInfo_S2U_BtcRank.Size(m)
}
func (m *S2U_BtcRank) XXX_DiscardUnknown() {
	xxx_messageInfo_S2U_BtcRank.DiscardUnknown(m)
}

var xxx_messageInfo_S2U_BtcRank proto.InternalMessageInfo

func (m *S2U_BtcRank) GetList() []*RankInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*U2S_Login)(nil), "msg.U2S_Login")
	proto.RegisterType((*S2U_LoginResult)(nil), "msg.S2U_LoginResult")
	proto.RegisterType((*U2S_RegistAccount)(nil), "msg.U2S_RegistAccount")
	proto.RegisterType((*G2U_RegistAccountResult)(nil), "msg.G2U_RegistAccountResult")
	proto.RegisterType((*S2U_PlayerBase)(nil), "msg.S2U_PlayerBase")
	proto.RegisterType((*S2U_Notice)(nil), "msg.S2U_Notice")
	proto.RegisterType((*U2S_Chat)(nil), "msg.U2S_Chat")
	proto.RegisterType((*S2U_Chat)(nil), "msg.S2U_Chat")
	proto.RegisterType((*U2S_ShopList)(nil), "msg.U2S_ShopList")
	proto.RegisterType((*ShopInfo)(nil), "msg.ShopInfo")
	proto.RegisterType((*S2U_ShopList)(nil), "msg.S2U_ShopList")
	proto.RegisterType((*U2S_Buy)(nil), "msg.U2S_Buy")
	proto.RegisterType((*S2U_BuyResult)(nil), "msg.S2U_BuyResult")
	proto.RegisterType((*U2S_MineMachineList)(nil), "msg.U2S_MineMachineList")
	proto.RegisterType((*MineMachine)(nil), "msg.MineMachine")
	proto.RegisterType((*S2U_MineMachineList)(nil), "msg.S2U_MineMachineList")
	proto.RegisterType((*U2S_MineList)(nil), "msg.U2S_MineList")
	proto.RegisterType((*MineInfo)(nil), "msg.MineInfo")
	proto.RegisterType((*S2U_MineList)(nil), "msg.S2U_MineList")
	proto.RegisterType((*U2S_Mining)(nil), "msg.U2S_Mining")
	proto.RegisterType((*S2U_MiningResult)(nil), "msg.S2U_MiningResult")
	proto.RegisterType((*U2S_GatherMine)(nil), "msg.U2S_GatherMine")
	proto.RegisterType((*S2U_GatherMine)(nil), "msg.S2U_GatherMine")
	proto.RegisterType((*U2S_StopMining)(nil), "msg.U2S_StopMining")
	proto.RegisterType((*S2U_StopMiningResult)(nil), "msg.S2U_StopMiningResult")
	proto.RegisterType((*U2S_ModifyPlayer)(nil), "msg.U2S_ModifyPlayer")
	proto.RegisterType((*S2U_ModifyPlayer)(nil), "msg.S2U_ModifyPlayer")
	proto.RegisterType((*U2S_Rank)(nil), "msg.U2S_Rank")
	proto.RegisterType((*RankInfo)(nil), "msg.RankInfo")
	proto.RegisterType((*S2U_AppCoinRank)(nil), "msg.S2U_AppCoinRank")
	proto.RegisterType((*S2U_BtcRank)(nil), "msg.S2U_BtcRank")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_0cde66bc4e56949c) }

var fileDescriptor_message_0cde66bc4e56949c = []byte{
	// 964 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xdf, 0x6e, 0xe3, 0xc4,
	0x17, 0x96, 0x9d, 0xb8, 0x4d, 0x4e, 0x9b, 0xfc, 0xfa, 0xf3, 0x16, 0x88, 0xaa, 0x15, 0x0a, 0xa3,
	0x15, 0xea, 0x0d, 0xd5, 0x12, 0x90, 0xb8, 0x00, 0x24, 0xb6, 0x49, 0x55, 0x45, 0x6a, 0x4a, 0x35,
	0x69, 0x97, 0x4b, 0x64, 0x9c, 0x59, 0x67, 0x54, 0x7b, 0xc6, 0xb2, 0xc7, 0x82, 0x20, 0xde, 0x88,
	0x1b, 0x9e, 0x01, 0x1e, 0x88, 0x57, 0x40, 0x67, 0xfe, 0xd8, 0x4e, 0x36, 0xaa, 0x2a, 0xae, 0xb8,
	0xca, 0xf9, 0x8e, 0xc7, 0x33, 0xe7, 0xfb, 0xce, 0x37, 0xc7, 0x81, 0x41, 0xc6, 0xca, 0x32, 0x4a,
	0xd8, 0x45, 0x5e, 0x48, 0x25, 0xc3, 0x4e, 0x56, 0x26, 0xe4, 0x2f, 0x0f, 0xfa, 0x0f, 0x93, 0xe5,
	0x8f, 0x37, 0x32, 0xe1, 0x22, 0xfc, 0x18, 0x60, 0xb9, 0x7a, 0x7c, 0x13, 0xc7, 0xb2, 0x12, 0x6a,
	0xe4, 0x8d, 0xbd, 0xf3, 0x3e, 0x6d, 0x65, 0xc2, 0x31, 0x1c, 0x2d, 0x57, 0x8f, 0xd3, 0x94, 0x33,
	0xa1, 0xe6, 0xb3, 0x91, 0xaf, 0x17, 0xb4, 0x53, 0xe1, 0xa7, 0x30, 0x34, 0xeb, 0x59, 0x59, 0xde,
	0xcb, 0x47, 0x26, 0x46, 0x1d, 0xbd, 0x68, 0x27, 0x1b, 0xbe, 0x84, 0xfe, 0x74, 0x1d, 0x09, 0xc1,
	0xd2, 0xf9, 0x6c, 0xd4, 0x1d, 0x7b, 0xe7, 0x01, 0x6d, 0x12, 0xe1, 0x08, 0x0e, 0xaf, 0xa3, 0x8c,
	0xbd, 0x65, 0xc5, 0xe8, 0x60, 0xec, 0x9d, 0x0f, 0xa8, 0x83, 0xe1, 0x29, 0x04, 0x57, 0xbf, 0xa8,
	0x22, 0x1a, 0x1d, 0xea, 0x6d, 0x0d, 0x20, 0x25, 0xfc, 0x6f, 0x39, 0x79, 0x30, 0x24, 0x28, 0x2b,
	0xab, 0x54, 0x85, 0x1f, 0xc2, 0x81, 0x89, 0x34, 0x8d, 0x01, 0xb5, 0x08, 0xb7, 0x76, 0xfc, 0x4c,
	0xf9, 0x0e, 0x62, 0x49, 0x78, 0x8a, 0xaa, 0xab, 0xee, 0xd0, 0x26, 0x11, 0x9e, 0x40, 0x67, 0x51,
	0x26, 0xba, 0xd4, 0x3e, 0xc5, 0x90, 0xfc, 0xed, 0xc1, 0xff, 0x51, 0x3a, 0xca, 0x12, 0x5e, 0x2a,
	0xb7, 0xcb, 0x7f, 0x45, 0xc2, 0x10, 0xba, 0xf3, 0x8c, 0xf1, 0x51, 0xa0, 0xdf, 0xd5, 0x31, 0x8a,
	0x77, 0xb7, 0x96, 0x82, 0x69, 0x51, 0xfb, 0xd4, 0x00, 0x5c, 0x79, 0x1b, 0x65, 0xcc, 0x2a, 0xaa,
	0x63, 0x5c, 0xb9, 0x54, 0x9b, 0x94, 0x8d, 0x7a, 0x5a, 0x3c, 0x03, 0xc8, 0x57, 0xf0, 0xd1, 0xf5,
	0xe4, 0x61, 0x9b, 0xb0, 0x95, 0xf5, 0x25, 0xf4, 0xaf, 0x8a, 0x42, 0x16, 0x53, 0xb9, 0x62, 0x9a,
	0x75, 0x40, 0x9b, 0x04, 0xf9, 0xd3, 0x83, 0x21, 0x36, 0xe8, 0x2e, 0x8d, 0x36, 0xac, 0xb8, 0x8c,
	0x4a, 0x16, 0x9e, 0x41, 0xcf, 0xa0, 0xf9, 0xcc, 0x76, 0xa8, 0xc6, 0x4f, 0xf4, 0xc8, 0xd5, 0xda,
	0xd9, 0x57, 0x6b, 0xb7, 0x55, 0x2b, 0xee, 0xff, 0x26, 0xcf, 0xa7, 0x92, 0x8b, 0x52, 0x6b, 0xe0,
	0xd3, 0x1a, 0x87, 0x04, 0x8e, 0xa7, 0x32, 0xcb, 0x2b, 0xc5, 0xee, 0xe4, 0xcf, 0xd6, 0x63, 0x3e,
	0xdd, 0xca, 0x61, 0xbf, 0x2f, 0x55, 0xac, 0x45, 0xf1, 0x29, 0x86, 0x64, 0x02, 0x80, 0x1c, 0x6e,
	0xa5, 0xe2, 0xb1, 0x56, 0xed, 0x7e, 0x93, 0x3b, 0xae, 0x3a, 0x76, 0x1e, 0xc1, 0x9a, 0x8f, 0x8d,
	0x47, 0x5e, 0x41, 0x0f, 0x2d, 0x32, 0x5d, 0x47, 0xda, 0x79, 0xb1, 0x14, 0x8a, 0x35, 0xac, 0x2c,
	0x24, 0xb7, 0xd0, 0xc3, 0x9d, 0xf5, 0xaa, 0x10, 0xba, 0x02, 0x19, 0x1a, 0xe7, 0xe8, 0xb8, 0x61,
	0xe8, 0xb7, 0x19, 0xb6, 0xf6, 0xeb, 0x6c, 0xef, 0x37, 0x84, 0x63, 0x3c, 0x75, 0xb9, 0x96, 0xf9,
	0x0d, 0x2f, 0x15, 0xf9, 0xc3, 0x83, 0x1e, 0x82, 0xb9, 0x78, 0x27, 0xb1, 0x53, 0x79, 0x21, 0x57,
	0x55, 0xac, 0xac, 0xf2, 0x01, 0x6d, 0x12, 0xf8, 0xb4, 0x60, 0x39, 0x2b, 0x94, 0x2c, 0x36, 0xfa,
	0xb8, 0x80, 0x36, 0x09, 0x14, 0x95, 0xa5, 0x2c, 0x56, 0x05, 0x8f, 0xf5, 0x99, 0x3e, 0xad, 0x31,
	0x1a, 0x3f, 0x8b, 0x44, 0x94, 0xb0, 0xa9, 0x2c, 0x95, 0xee, 0x85, 0x4f, 0x5b, 0x19, 0xbc, 0x90,
	0xb2, 0x52, 0x79, 0xa5, 0x6c, 0x3b, 0x2c, 0x42, 0x72, 0x79, 0xc1, 0x63, 0x66, 0xbb, 0x60, 0x00,
	0xf9, 0x1c, 0x8e, 0x51, 0x12, 0x47, 0x21, 0xfc, 0x04, 0xba, 0x29, 0x2f, 0xf1, 0x42, 0x75, 0xce,
	0x8f, 0x26, 0x83, 0x8b, 0xac, 0x4c, 0x2e, 0x1c, 0x25, 0xaa, 0x1f, 0x91, 0x6f, 0xe1, 0x10, 0x59,
	0x5f, 0x56, 0x1b, 0x64, 0x71, 0xb7, 0xcb, 0xb1, 0x4e, 0xe0, 0x89, 0xd3, 0xda, 0x5c, 0x01, 0x35,
	0x80, 0x7c, 0x06, 0x03, 0x3c, 0xf1, 0xb2, 0xda, 0x3c, 0xcb, 0xd2, 0x1f, 0xc0, 0x0b, 0x3c, 0x6d,
	0xc1, 0x05, 0x5b, 0x44, 0xf1, 0x9a, 0x0b, 0xa6, 0xa5, 0xfe, 0xdd, 0x83, 0xa3, 0x56, 0x2e, 0x1c,
	0x82, 0x5f, 0x97, 0xe0, 0x1b, 0x7d, 0x9b, 0xca, 0xfc, 0xdd, 0xca, 0xce, 0xa0, 0x77, 0x23, 0xe3,
	0x48, 0x71, 0x69, 0x2e, 0x7d, 0x40, 0x6b, 0x8c, 0xed, 0xa6, 0x95, 0xb8, 0xe7, 0x99, 0x31, 0x7a,
	0x87, 0x3a, 0x88, 0x4f, 0xae, 0xc4, 0x4a, 0x3f, 0x09, 0xcc, 0x13, 0x0b, 0xb1, 0x27, 0xdf, 0x6b,
	0x95, 0xd1, 0xf7, 0x56, 0xe0, 0x56, 0x86, 0x7c, 0x0d, 0x2f, 0x90, 0xf3, 0x0e, 0x89, 0xf0, 0xd5,
	0x96, 0xd8, 0x27, 0x5a, 0xec, 0xd6, 0x1a, 0xab, 0xb7, 0x75, 0xd9, 0xc2, 0x51, 0xff, 0x0d, 0x7a,
	0x18, 0x6b, 0x93, 0xb5, 0x89, 0x78, 0x3b, 0x44, 0xce, 0xa0, 0x77, 0xe5, 0x4c, 0xe4, 0x1b, 0x13,
	0x39, 0x8c, 0x37, 0xe8, 0x9e, 0xe7, 0xd6, 0x5b, 0x18, 0x62, 0xb3, 0x28, 0xbe, 0x67, 0x1d, 0x65,
	0x00, 0xae, 0xbb, 0xad, 0x32, 0x4d, 0x37, 0xa0, 0x18, 0x3a, 0xc3, 0xb8, 0x6a, 0xf6, 0x1a, 0xc6,
	0x95, 0x67, 0x09, 0x50, 0x00, 0x4b, 0x80, 0x8b, 0xe4, 0xbd, 0x4e, 0xb5, 0x29, 0xf8, 0xef, 0xf7,
	0xe2, 0x07, 0x9e, 0xa6, 0xb3, 0x68, 0x63, 0xdb, 0xe4, 0x20, 0xf9, 0x0e, 0x4e, 0x6c, 0x19, 0x5c,
	0x24, 0xd6, 0x48, 0x7b, 0x3c, 0xd0, 0x18, 0xcb, 0xdf, 0x35, 0xd6, 0x37, 0x30, 0xc4, 0xaa, 0xae,
	0x23, 0xb5, 0x66, 0xc5, 0x62, 0x9f, 0x87, 0x9e, 0xa8, 0x8c, 0x4c, 0xcc, 0xa0, 0x7d, 0xe2, 0x6d,
	0x3b, 0xd8, 0xfc, 0x66, 0xb0, 0x8d, 0xcd, 0x89, 0x4b, 0x25, 0xf3, 0xfd, 0x5a, 0x90, 0x19, 0x9c,
	0xea, 0xdb, 0x58, 0xaf, 0xf8, 0x97, 0xcc, 0x4e, 0xb4, 0xde, 0x72, 0xc5, 0xdf, 0x6d, 0xcc, 0xb0,
	0xaf, 0x07, 0xba, 0xb7, 0x6f, 0xa0, 0xb7, 0xc7, 0x1d, 0x79, 0x6d, 0x95, 0x6d, 0xbf, 0xfd, 0xf4,
	0x15, 0x05, 0x33, 0x7c, 0x69, 0x24, 0x1e, 0xc9, 0xaf, 0xd0, 0xc3, 0x5f, 0x6d, 0x4e, 0x3c, 0x53,
	0xd6, 0x9f, 0x1d, 0x1d, 0x6f, 0x7d, 0x8e, 0xfc, 0x9d, 0xcf, 0xd1, 0xf3, 0x3f, 0x3a, 0xa7, 0x10,
	0xbc, 0x8d, 0xd2, 0x8a, 0xd9, 0x11, 0x67, 0x00, 0xf9, 0xd2, 0xfc, 0x3b, 0xb1, 0x9f, 0x1f, 0x2c,
	0x63, 0xaf, 0x3b, 0x5d, 0x7d, 0xd6, 0x9d, 0xaf, 0xe1, 0x48, 0xcf, 0x23, 0x15, 0x3f, 0xf3, 0x8d,
	0x9f, 0x0e, 0xf4, 0xff, 0xba, 0x2f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xa9, 0x5c, 0xde,
	0xe8, 0x09, 0x00, 0x00,
}
